run-name: Ejecutado por ${{ github.actor }}

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Detectar microservicios modificados
        id: detect
        uses: tj-actions/changed-files@v34
        with:
          files: 'Micros/**'
        
      - name: Establecer microservicios modificados
        id: set-changes
        run: |
          echo "changed=$(echo ${{ steps.detect.outputs.all_changed_files }} | grep -o 'Micros/[^/]*' | sort -u | paste -sd, -)" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.changed_services) }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar script de CI/CD
        run: bash ${{ matrix.service }}/example1.sh || bash ${{ matrix.service }}/example2.sh || bash ${{ matrix.service }}/example3.sh
